/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/{tenant_slug}/servicios/{servicio_id}/disponibilidad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disponibilidad Por Dia */
        get: operations["disponibilidad_por_dia_api_v2__tenant_slug__servicios__servicio_id__disponibilidad_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/{tenant_slug}/servicios/{servicio_id}/sesiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Sesiones Abiertas */
        get: operations["listar_sesiones_abiertas_api_v2__tenant_slug__servicios__servicio_id__sesiones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/{tenant_slug}/sesiones/{sesion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle Sesion */
        get: operations["detalle_sesion_api_v2__tenant_slug__sesiones__sesion_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/{tenant_slug}/sesiones/{sesion_id}/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle Sesion Admin */
        get: operations["detalle_sesion_admin_api_v2__tenant_slug__sesiones__sesion_id__admin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/{tenant_slug}/reservas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear Nueva Reserva */
        post: operations["crear_nueva_reserva_api_v2__tenant_slug__reservas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/{tenant_slug}/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook Stripe */
        post: operations["webhook_stripe_api_v2__tenant_slug__webhooks_stripe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/{tenant_slug}/reservas/{folio}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Reserva */
        get: operations["consultar_reserva_api_v2__tenant_slug__reservas__folio__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/{tenant_slug}/mis-reservas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Mis Reservas */
        get: operations["listar_mis_reservas_api_v2__tenant_slug__mis_reservas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/{tenant_slug}/reservas/{folio}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Checkin Reserva */
        post: operations["checkin_reserva_api_v2__tenant_slug__reservas__folio__checkin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/{tenant_slug}/reservas/{folio}/cancelar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancelar Reserva Endpoint */
        post: operations["cancelar_reserva_endpoint_api_v2__tenant_slug__reservas__folio__cancelar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/{tenant_slug}/sesiones/{sesion_id}/reagendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reagendar Sesion Endpoint */
        post: operations["reagendar_sesion_endpoint_api_v2__tenant_slug__sesiones__sesion_id__reagendar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/{tenant_slug}/sesiones/{sesion_id}/completar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Completar Sesion Endpoint */
        post: operations["completar_sesion_endpoint_api_v2__tenant_slug__sesiones__sesion_id__completar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Endpoint de salud. Lo usa Docker, Railway, Render, etc.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AsesorPublicOut
         * @description Datos de asesor visibles al público. Sin email, sin comisión, sin metadata.
         */
        AsesorPublicOut: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Bio */
            bio?: string | null;
        };
        /**
         * CanalEnum
         * @enum {string}
         */
        CanalEnum: "web" | "admin" | "whatsapp" | "api";
        /** CancelarReservaIn */
        CancelarReservaIn: {
            /** Motivo */
            motivo?: string | null;
        };
        /** CheckoutUrlOut */
        CheckoutUrlOut: {
            /** Url */
            url: string;
            /** Proveedor */
            proveedor: string;
            /** Expira En */
            expira_en?: string | null;
        };
        /** DisponibilidadDiaOut */
        DisponibilidadDiaOut: {
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
            /** Servicio Id */
            servicio_id: number;
            /** Timezone */
            timezone: string;
            /** Slots */
            slots: components["schemas"]["SlotDisponible"][];
        };
        /**
         * EstadoPagoEnum
         * @enum {string}
         */
        EstadoPagoEnum: "pendiente" | "completado" | "reembolsado" | "exento";
        /**
         * EstadoReservaEnum
         * @enum {string}
         */
        EstadoReservaEnum: "pendiente" | "en_espera" | "confirmada" | "cancelada" | "no_show" | "completada";
        /**
         * EstadoSesionEnum
         * @enum {string}
         */
        EstadoSesionEnum: "abierta" | "confirmada" | "llena" | "cancelada" | "completada";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MetodoPagoEnum
         * @enum {string}
         */
        MetodoPagoEnum: "online" | "local" | "registro";
        /**
         * ModalidadEnum
         * @enum {string}
         */
        ModalidadEnum: "presencial" | "virtual" | "hibrida";
        /** OperacionOut */
        OperacionOut: {
            /** Ok */
            ok: boolean;
            /** Mensaje */
            mensaje: string;
            /** Detalle */
            detalle?: Record<string, never> | null;
        };
        /** PaginacionOut */
        PaginacionOut: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** ReagendarSesionIn */
        ReagendarSesionIn: {
            /**
             * Nueva Fecha Hora Inicio
             * Format: date-time
             */
            nueva_fecha_hora_inicio: string;
            /** Nuevo Asesor Id */
            nuevo_asesor_id?: number | null;
            /** Nueva Sede Id */
            nueva_sede_id?: number | null;
            /** Motivo */
            motivo?: string | null;
        };
        /** ReservaCreate */
        ReservaCreate: {
            /** Servicio Id */
            servicio_id: number;
            /**
             * Fecha Hora Inicio
             * Format: date-time
             */
            fecha_hora_inicio: string;
            /**
             * Sesion Id
             * @description ID de la sesión existente a la que el cliente eligió unirse. Si se omite, el sistema busca o crea una sesión.
             */
            sesion_id?: number | null;
            /**
             * Asesor Id
             * @description Solo aplica cuando sesion_id es nulo y el tenant permite elegir asesor.
             */
            asesor_id?: number | null;
            /** Sede Id */
            sede_id?: number | null;
            /** Beneficiario Id */
            beneficiario_id?: number | null;
            /** Notas Cliente */
            notas_cliente?: string | null;
            metodo_pago?: components["schemas"]["MetodoPagoEnum"] | null;
            /** @default web */
            canal: components["schemas"]["CanalEnum"];
            /** Email Invitado */
            email_invitado?: string | null;
            /** Nombre Invitado */
            nombre_invitado?: string | null;
            /** Telefono Invitado */
            telefono_invitado?: string | null;
            /** Respuestas Formulario */
            respuestas_formulario?: Record<string, never> | null;
        };
        /**
         * ReservaCreateResponse
         * @description Respuesta del POST /reservas.
         *
         *     v2.1 devolvía `SesionOut`, un nombre que nunca se importó en el router: el
         *     endpoint lanzaba NameError DESPUÉS de haber creado la reserva y cobrado.
         */
        ReservaCreateResponse: {
            reserva: components["schemas"]["ReservaOut"];
            checkout?: components["schemas"]["CheckoutUrlOut"] | null;
            /** Mensaje */
            mensaje: string;
            /** Sesion Asignada Id */
            sesion_asignada_id: number;
            /**
             * Sesion Creada
             * @description True si se creó una sesión nueva; False si el cliente se unió a una existente.
             */
            sesion_creada: boolean;
        };
        /** ReservaOut */
        ReservaOut: {
            /** Id */
            id: number;
            /** Folio */
            folio: string;
            /** Codigo Confirmacion */
            codigo_confirmacion: string;
            estado: components["schemas"]["EstadoReservaEnum"];
            estado_pago: components["schemas"]["EstadoPagoEnum"];
            /** Sesion Id */
            sesion_id: number;
            /** Servicio Id */
            servicio_id: number;
            /** Servicio Nombre */
            servicio_nombre?: string | null;
            /**
             * Fecha Hora Inicio
             * Format: date-time
             */
            fecha_hora_inicio: string;
            /**
             * Fecha Hora Fin
             * Format: date-time
             */
            fecha_hora_fin: string;
            /** Timezone */
            timezone: string;
            modalidad?: components["schemas"]["ModalidadEnum"] | null;
            /** Precio Final */
            precio_final?: string | null;
            /**
             * Moneda
             * @default MXN
             */
            moneda: string;
            /** Meet Url */
            meet_url?: string | null;
            sede?: components["schemas"]["SedeOut"] | null;
            asesor?: components["schemas"]["AsesorPublicOut"] | null;
            /** Hold Expira En */
            hold_expira_en?: string | null;
            /** Notas Cliente */
            notas_cliente?: string | null;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
        };
        /** ReservaResumenAdminOut */
        ReservaResumenAdminOut: {
            /** Id */
            id: number;
            /** Folio */
            folio: string;
            estado: components["schemas"]["EstadoReservaEnum"];
            estado_pago: components["schemas"]["EstadoPagoEnum"];
            /** Nombre Cliente */
            nombre_cliente?: string | null;
            /** Email Cliente */
            email_cliente?: string | null;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
        };
        /** SedeOut */
        SedeOut: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Direccion */
            direccion?: string | null;
            /** Direccion Completa */
            direccion_completa?: string | null;
            /** Mapa Url */
            mapa_url?: string | null;
            /** Telefono */
            telefono?: string | null;
            /** Timezone */
            timezone: string;
        };
        /** SesionAdminOut */
        SesionAdminOut: {
            /** Id */
            id: number;
            /** Servicio Id */
            servicio_id: number;
            /**
             * Fecha Hora Inicio
             * Format: date-time
             */
            fecha_hora_inicio: string;
            /**
             * Fecha Hora Fin
             * Format: date-time
             */
            fecha_hora_fin: string;
            /** Timezone */
            timezone: string;
            estado: components["schemas"]["EstadoSesionEnum"];
            /** Cupo Maximo */
            cupo_maximo: number;
            /** Inscritos */
            inscritos: number;
            /** Lugares Disponibles */
            lugares_disponibles: number;
            asesor?: components["schemas"]["AsesorPublicOut"] | null;
            sede?: components["schemas"]["SedeOut"] | null;
            modalidad?: components["schemas"]["ModalidadEnum"] | null;
            /** Servicio Nombre */
            servicio_nombre?: string | null;
            /** Duracion Minutos */
            duracion_minutos?: number | null;
            /** Precio */
            precio?: string | null;
            /** Moneda */
            moneda?: string | null;
            /** Meet Url */
            meet_url?: string | null;
            /** Notas Internas */
            notas_internas?: string | null;
            /** Google Event Id */
            google_event_id?: string | null;
            /** Creado Por Tipo */
            creado_por_tipo?: string | null;
            /** Creado En */
            creado_en?: string | null;
            /** Version Id */
            version_id?: number | null;
            /** Reservas */
            reservas?: components["schemas"]["ReservaResumenAdminOut"][];
        };
        /**
         * SesionDetailOut
         * @description Detalle público de una sesión.
         *
         *     ELIMINADO respecto de v2.1: la lista `reservas` con folio y estado de cada
         *     inscrito, y `notas_internas`. El endpoint era anónimo y sesion_id es
         *     autoincremental, así que cualquiera podía iterar IDs, cosechar folios y
         *     consultar el historial de pago ajeno. Para la vista completa existe
         *     SesionAdminOut, detrás de autenticación con rol.
         */
        SesionDetailOut: {
            /** Id */
            id: number;
            /** Servicio Id */
            servicio_id: number;
            /**
             * Fecha Hora Inicio
             * Format: date-time
             */
            fecha_hora_inicio: string;
            /**
             * Fecha Hora Fin
             * Format: date-time
             */
            fecha_hora_fin: string;
            /** Timezone */
            timezone: string;
            estado: components["schemas"]["EstadoSesionEnum"];
            /** Cupo Maximo */
            cupo_maximo: number;
            /** Inscritos */
            inscritos: number;
            /** Lugares Disponibles */
            lugares_disponibles: number;
            asesor?: components["schemas"]["AsesorPublicOut"] | null;
            sede?: components["schemas"]["SedeOut"] | null;
            modalidad?: components["schemas"]["ModalidadEnum"] | null;
            /** Servicio Nombre */
            servicio_nombre?: string | null;
            /** Duracion Minutos */
            duracion_minutos?: number | null;
            /** Precio */
            precio?: string | null;
            /** Moneda */
            moneda?: string | null;
            /** Meet Url */
            meet_url?: string | null;
        };
        /**
         * SesionListOut
         * @description Vista de listado. Sin datos de otros clientes.
         */
        SesionListOut: {
            /** Id */
            id: number;
            /** Servicio Id */
            servicio_id: number;
            /**
             * Fecha Hora Inicio
             * Format: date-time
             */
            fecha_hora_inicio: string;
            /**
             * Fecha Hora Fin
             * Format: date-time
             */
            fecha_hora_fin: string;
            /** Timezone */
            timezone: string;
            estado: components["schemas"]["EstadoSesionEnum"];
            /** Cupo Maximo */
            cupo_maximo: number;
            /** Inscritos */
            inscritos: number;
            /** Lugares Disponibles */
            lugares_disponibles: number;
            asesor?: components["schemas"]["AsesorPublicOut"] | null;
            sede?: components["schemas"]["SedeOut"] | null;
        };
        /** SesionesPaginadasOut */
        SesionesPaginadasOut: {
            /** Items */
            items: components["schemas"]["SesionListOut"][];
            paginacion: components["schemas"]["PaginacionOut"];
        };
        /** SlotDisponible */
        SlotDisponible: {
            /**
             * Fecha Hora Inicio
             * Format: date-time
             */
            fecha_hora_inicio: string;
            /**
             * Fecha Hora Fin
             * Format: date-time
             */
            fecha_hora_fin: string;
            /** Disponible */
            disponible: boolean;
            /** Sesion Existente Id */
            sesion_existente_id?: number | null;
            /** Cupo Disponible */
            cupo_disponible?: number | null;
            asesor?: components["schemas"]["AsesorPublicOut"] | null;
            /** Motivo No Disponible */
            motivo_no_disponible?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    disponibilidad_por_dia_api_v2__tenant_slug__servicios__servicio_id__disponibilidad_get: {
        parameters: {
            query: {
                /** @description Fecha con offset, ej. 2026-08-01T00:00:00-06:00 */
                fecha: string;
                asesor_id?: number | null;
            };
            header?: never;
            path: {
                servicio_id: number;
                tenant_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisponibilidadDiaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_sesiones_abiertas_api_v2__tenant_slug__servicios__servicio_id__sesiones_get: {
        parameters: {
            query?: {
                desde?: string | null;
                hasta?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                servicio_id: number;
                tenant_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionesPaginadasOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detalle_sesion_api_v2__tenant_slug__sesiones__sesion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesion_id: number;
                tenant_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detalle_sesion_admin_api_v2__tenant_slug__sesiones__sesion_id__admin_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesion_id: number;
                tenant_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionAdminOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_nueva_reserva_api_v2__tenant_slug__reservas_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReservaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservaCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    webhook_stripe_api_v2__tenant_slug__webhooks_stripe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    consultar_reserva_api_v2__tenant_slug__reservas__folio__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folio: string;
                tenant_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_mis_reservas_api_v2__tenant_slug__mis_reservas_get: {
        parameters: {
            query?: {
                incluir_pasadas?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                tenant_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReservaOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkin_reserva_api_v2__tenant_slug__reservas__folio__checkin_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folio: string;
                tenant_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperacionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancelar_reserva_endpoint_api_v2__tenant_slug__reservas__folio__cancelar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                folio: string;
                tenant_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelarReservaIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperacionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reagendar_sesion_endpoint_api_v2__tenant_slug__sesiones__sesion_id__reagendar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesion_id: number;
                tenant_slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReagendarSesionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    completar_sesion_endpoint_api_v2__tenant_slug__sesiones__sesion_id__completar_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesion_id: number;
                tenant_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperacionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
